workflows:
  ios-release-workflow:
    name: TifoFlash iOS Release Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: appstore_key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize keychain on build machine
        script: |
          keychain initialize

      - name: Fetch Flutter dependencies
        script: |
          cd tifoflash_app
          flutter pub get

      - name: Fetch signing certificates from Apple
        script: |
          app-store-connect fetch-signing-files "com.tifoflash.tifoflashApp" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Build & Sign iOS IPA Package
        script: |
          cd tifoflash_app
          flutter build ipa --release

    artifacts:
      - tifoflash_app/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        api_key: appstore_key
        submit_to_testflight: true
        submit_to_app_store: false

  android-release-workflow:
    name: TifoFlash Android Release Workflow (APK & AAB)
    max_build_duration: 30
    instance_type: linux
    environment:
      flutter: stable
    scripts:
      - name: Fetch Flutter dependencies
        script: |
          cd tifoflash_app
          flutter pub get
      - name: Build Android APK & App Bundle (AAB)
        script: |
          cd tifoflash_app
          flutter build apk --release
          flutter build appbundle --release
    artifacts:
      - tifoflash_app/build/app/outputs/flutter-apk/*.apk
      - tifoflash_app/build/app/outputs/bundle/release/*.aab
